In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("movies_metadata.csv")

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [6]:
df.shape

(45466, 24)

In [7]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [8]:
df = df.drop_duplicates()

In [9]:
df.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0

In [10]:
features = [
    "title",
    "genres",
    "overview",
    "tagline",
    "production_companies",
    "spoken_languages",
    "vote_average",
    "popularity"
]
df = df[features]

In [11]:
df.shape

(45453, 8)

In [12]:
df.isnull().sum()

title                       6
genres                      0
overview                  954
tagline                 25045
production_companies        3
spoken_languages            6
vote_average                6
popularity                  5
dtype: int64

In [13]:
df = df.dropna(subset =['title'])

In [14]:
import ast
df['genres'] = df['genres'].apply(lambda x : ' '.join(i['name'] for i in ast.literal_eval(x)))

In [15]:
df['overview'] = df['overview'].fillna('')
df['tagline'] = df['tagline'].fillna('')
df["production_companies"] = df['production_companies'].fillna("")
df["spoken_languages"] = df['spoken_languages'].fillna(df['spoken_languages'].mode())
df['vote_average'] = df['vote_average'].fillna(df['vote_average'].median())

In [16]:
df.isnull().sum()

title                   0
genres                  0
overview                0
tagline                 0
production_companies    0
spoken_languages        0
vote_average            0
popularity              0
dtype: int64

In [17]:
df.head()

,title,genres,overview,tagline,production_companies,spoken_languages,vote_average,popularity
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_639_1': 'en', 'name': 'English'}]",7.7,21.946943
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",6.9,17.015539
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_639_1': 'en', 'name': 'English'}]",6.5,11.7129
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_639_1': 'en', 'name': 'English'}]",6.1,3.859495
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_639_1': 'en', 'name': 'English'}]",5.7,8.387519

In [18]:
df['production_companies'] = df['production_companies'].apply(lambda x : " ".join(i['name'] for i in ast.literal_eval(x)))

In [19]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x : " ".join(i["name"] for i in ast.literal_eval(x)))

In [20]:
df.head()

,title,genres,overview,tagline,production_companies,spoken_languages,vote_average,popularity
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,Pixar Animation Studios,English,7.7,21.946943
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,TriStar Pictures Teitler Film Interscope Commu...,English Français,6.9,17.015539
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Warner Bros. Lancaster Gate,English,6.5,11.7129
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Twentieth Century Fox Film Corporation,English,6.1,3.859495
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Sandollar Productions Touchstone Pictures,English,5.7,8.387519

In [21]:
df["tags"] = (
    df["title"] + " " +
    df["title"] + " " +
    df["overview"] + " " +
    df["genres"] + " " +
    df["tagline"]
)

In [22]:
df.head()

,title,genres,overview,tagline,production_companies,spoken_languages,vote_average,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,Pixar Animation Studios,English,7.7,21.946943,"Toy Story Toy Story Led by Woody, Andy's toys ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,TriStar Pictures Teitler Film Interscope Commu...,English Français,6.9,17.015539,Jumanji Jumanji When siblings Judy and Peter d...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Warner Bros. Lancaster Gate,English,6.5,11.7129,Grumpier Old Men Grumpier Old Men A family wed...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Twentieth Century Fox Film Corporation,English,6.1,3.859495,Waiting to Exhale Waiting to Exhale Cheated on...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Sandollar Productions Touchstone Pictures,English,5.7,8.387519,Father of the Bride Part II Father of the Brid...

In [23]:
df['tags'][1]

"Jumanji Jumanji When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [24]:
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [25]:
df['tags'] = df["tags"].apply(lambda x : x.lower())

In [26]:
df['tags'][0]

"toy story toy story led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences. animation comedy family "

In [27]:
import string 
def remove_puc (txt) : 
    return txt.translate(str.maketrans("","",string.punctuation))
df['tags'] = df['tags'].apply(remove_puc)

In [28]:
df['tags'][1]

'jumanji jumanji when siblings judy and peter discover an enchanted board game that opens the door to a magical world they unwittingly invite alan  an adult whos been trapped inside the game for 26 years  into their living room alans only hope for freedom is to finish the game which proves risky as all three find themselves running from giant rhinoceroses evil monkeys and other terrifying creatures adventure fantasy family roll the dice and unleash the excitement'

In [29]:
#nltk.download('wordnet')
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()
from nltk.tokenize import word_tokenize
def remove(txt):
    words = word_tokenize(txt)
    cleaned= []
    for i in words:
        if not i in stop_words:
            cleaned.append(lemmatizer.lemmatize(i))
    return " ".join(cleaned)
df['tags'] = df['tags'].apply(remove)

In [30]:
df['tags'][1]

'jumanji jumanji sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [31]:
df = df.reset_index(drop = True)

In [32]:
indices = pd.Series(df.index , index = df['title'])
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [33]:
df.head()

,title,genres,overview,tagline,production_companies,spoken_languages,vote_average,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,Pixar Animation Studios,English,7.7,21.946943,toy story toy story led woody andys toy live h...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,TriStar Pictures Teitler Film Interscope Commu...,English Français,6.9,17.015539,jumanji jumanji sibling judy peter discover en...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Warner Bros. Lancaster Gate,English,6.5,11.7129,grumpier old men grumpier old men family weddi...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Twentieth Century Fox Film Corporation,English,6.1,3.859495,waiting exhale waiting exhale cheated mistreat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Sandollar Productions Touchstone Pictures,English,5.7,8.387519,father bride part ii father bride part ii geor...

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words='english',
    ngram_range=(1,2),
    min_df=2
)

tfidf_matrix = tfidf.fit_transform(df['tags'])

In [35]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1304604 stored elements and shape (45447, 10000)>

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

In [37]:
n = 10

def recommend(title):
    matches = df[
        df['title'].str.contains(title, case=False, na=False)
    ]
    
    if matches.empty:
        return ["Movie not found"]
    
   
    idx = matches.index[0]

    sim_score = similarity[idx]

    similar_idx = sim_score.argsort()[::-1]

    filtered_idx = [
        i for i in similar_idx
        if sim_score[i] > 0.1
    ]

    return df['title'].iloc[filtered_idx[1:n+1]]

In [38]:
recommend("Batman")

19785              Batman: The Dark Knight Returns, Part 1
35965                                    Batman: Bad Blood
41963    Batman Beyond Darwyn Cooke's Batman 75th Anniv...
21186    Batman Unmasked: The Psychology of the Dark Kn...
44961                             Batman Beyond: The Movie
3094                          Batman: Mask of the Phantasm
10119                                        Batman Begins
43760                                        Batman & Bill
20225              Batman: The Dark Knight Returns, Part 2
1328                                        Batman Returns
Name: title, dtype: object

In [39]:
import pickle
pickle.dump(tfidf_matrix,open("tfidf_matrix.pkl","wb"))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle("df.pkl")
pickle.dump(tfidf , open("tfidf.pkl","wb"))